// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzWlGlxHMVpwfMvgFTDktWhhja9QPa7h0',
    appId: '1:243932113368:web:0f76c65cc650f543352aad',
    messagingSenderId: '243932113368',
    projectId: 'diagnos-it',
    authDomain: 'diagnos-it.firebaseapp.com',
    storageBucket: 'diagnos-it.appspot.com',
    measurementId: 'G-W2474ZZTWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5h1a-Se0T7VCZTN0vdIKHeZ0q-_rtc18',
    appId: '1:243932113368:android:d6b7b497d9aab618352aad',
    messagingSenderId: '243932113368',
    projectId: 'diagnos-it',
    storageBucket: 'diagnos-it.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWu1YS-fUyJt2ZXpsrL8j9hzbnjwGsopg',
    appId: '1:243932113368:ios:c464a4cbc2f34c17352aad',
    messagingSenderId: '243932113368',
    projectId: 'diagnos-it',
    storageBucket: 'diagnos-it.appspot.com',
    iosBundleId: 'com.example.canvas',
  );
}
